### ISSUE TITLE
"List my PRs" command

### ISSUE THREAD

**Issue by joshmoore** [openmicroscopy/snoopycrimecop#42]
`scc list-prs --assigned=me` or similar (possibly re-using the parsing done for gh-39) should be available. Optimally, it would find all of your organizations (and all of the repos to which you've been added) and then list all PRs which were created, assigned, etc. to you, possibly listing open versus closed ones.

The first goal would be to print out the urls of all the PRs which have been assigned to me which are still open so that I can review them first thing in the morning as a replacement/extension of the standup.

/cc @sbesson

**Comment by sbesson** [comment]
GitHub has introduced a nice API for that - see https://github.com/pulls/assigned. Is this still valid or is the UI mentioned above effectively covering these needs.
